spring.application.name=EmailService

server.port = 9093

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=vitthalkkhemnar@gmail.com
spring.mail.password=cbfg hbqn xnwz uwbw

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true